[build-system]
build-backend = "scikit_build_core.build"
requires = [
    "cython>=3.0.0",
    "scikit-build-core",
]

[project]
name = "pkg1"
version = "1.0.0"

[tool.scikit-build]
ninja.make-fallback = false
cmake.args = [
    "-DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake",
    "-DVCPKG_INSTALLED_DIR=./vcpkg_installed",
    "-DBUILD_PYTHON_EXTENSION=ON"
]